import type { PresentationSpec, PresentationSlide } from "./spec";
import type { ComparePresentationSpec } from "./studio";

type AnySpec = PresentationSpec | ComparePresentationSpec | Record<string, unknown>;

function slidesOf(spec: AnySpec): PresentationSlide[] {
  const slides = (spec as { slides?: PresentationSlide[] }).slides;
  return Array.isArray(slides) ? slides : [];
}

function titleOf(spec: AnySpec): string {
  return String((spec as { title?: string }).title ?? "PropPilot presentation");
}

export function exportPresentationMarkdown(spec: AnySpec): string {
  const lines: string[] = [`# ${titleOf(spec)}`, ""];
  for (const slide of slidesOf(spec)) {
    if (slide.type === "cover") {
      lines.push(`## ${slide.title}`, "", slide.subtitle, "", `_${slide.location}_`, "");
    } else if (slide.type === "facts") {
      lines.push(`## ${slide.title}`, "");
      for (const row of slide.rows) lines.push(`- **${row.label}:** ${row.value}`);
      lines.push("");
    } else if (slide.type === "amenities") {
      lines.push(`## ${slide.title}`, "", slide.items.map((i) => `- ${i}`).join("\n"), "");
    } else if (slide.type === "spatial") {
      lines.push(
        `## ${slide.title}`,
        "",
        slide.caption,
        "",
        `_Layout: ${slide.layoutHint} · renderer: ${slide.renderer}_`,
        "",
      );
    } else {
      lines.push(`## ${slide.title}`, "", slide.body, "");
    }
  }
  lines.push("---", "_Generated by PropPilot from PropertyGateway facts only._");
  return lines.join("\n");
}

/** Lightweight PPTX-shaped JSON for downstream workers (no binary dependency). */
export function exportPresentationPptxJson(spec: AnySpec): Record<string, unknown> {
  return {
    format: "proppilot.pptx-json",
    version: 1,
    title: titleOf(spec),
    themeId: (spec as { themeId?: string }).themeId ?? "marina",
    slides: slidesOf(spec).map((slide, index) => {
      if (slide.type === "cover") {
        return {
          index,
          layout: "title",
          title: slide.title,
          subtitle: slide.subtitle,
          notes: slide.location,
        };
      }
      if (slide.type === "facts") {
        return {
          index,
          layout: "two_column_table",
          title: slide.title,
          rows: slide.rows,
        };
      }
      if (slide.type === "amenities") {
        return {
          index,
          layout: "bullets",
          title: slide.title,
          bullets: slide.items,
        };
      }
      if (slide.type === "spatial") {
        return {
          index,
          layout: "spatial_placeholder",
          title: slide.title,
          caption: slide.caption,
          layoutHint: slide.layoutHint,
          renderer: slide.renderer,
        };
      }
      return {
        index,
        layout: "body",
        title: slide.title,
        body: slide.body,
      };
    }),
    generatedAt: new Date().toISOString(),
    source: (spec as { source?: string }).source ?? "property_gateway",
  };
}

export type ExportFormat = "md" | "json" | "pptx-json";

export function exportPresentation(spec: AnySpec, format: ExportFormat): {
  contentType: string;
  body: string;
  filename: string;
} {
  const slug = titleOf(spec)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 48);
  if (format === "md") {
    return {
      contentType: "text/markdown; charset=utf-8",
      body: exportPresentationMarkdown(spec),
      filename: `${slug || "presentation"}.md`,
    };
  }
  if (format === "pptx-json") {
    return {
      contentType: "application/json; charset=utf-8",
      body: JSON.stringify(exportPresentationPptxJson(spec), null, 2),
      filename: `${slug || "presentation"}.pptx.json`,
    };
  }
  return {
    contentType: "application/json; charset=utf-8",
    body: JSON.stringify(spec, null, 2),
    filename: `${slug || "presentation"}.json`,
  };
}
